### ISSUE TITLE
Ideias de Projeto

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#1]
## Nome da Issue
Ideias de Projeto

## Descrição da Issue
Pensar em ideias para o projeto de desenho

### Tasks:
- [x] Elaborar situação problema
- [x] Elaborar solução
- [x] Elaborar principais funcionalidades

**Comment by devsalula** [comment]
Todas as ideias estão sendo colocadas nesse [documento](https://docs.google.com/document/d/1r9eLWrKHS8HU8mu-nYRHPjDWWwhRspTUgCx5RB3L6S4/edit)

**Comment by shayanealcantara** [comment]
Por meio de votação com os membros do grupo e feedback da professora, o projeto escolhido foi o "Restaurante com QR Code".
