### ISSUE TITLE
US31 Finalização de pedidos 

### ISSUE THREAD

**Issue by pedro-prp** [fga-desenho-2019-2/Wiki#102]
**Descrição**
Eu, como cliente, gostaria de finalizar o meu pedido para comer.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- Deverá ter um pop up de confirmação do pedido;
- Deverá ser integrado com o serviço de Pedidos;
- Funcionalidade testada

**Tarefas**
- [x] Criar pop up de confirmação de pedido.
- [x] Integrar com o backend de pedidos

**Comment by MatheusBlanco** [comment]
conversar com a outra dupla pra ver quem arruma o que e fazer os testes
