### ISSUE TITLE
Fish Bone (Causa e efeito)

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#11]
## Nome da Issue
Fish Bone (Causa e efeito)

## Descrição da Issue
Construir diagrama de causa e efeito, para explicar as possíveis causas do problema que nossa solução promete solucionar (filas em praça de alimentação)

### Tasks:
- [x] Construir Diagrama
- [x] Pensar possíveis causas do problema

**Comment by silvasara** [comment]
Falta apenas um tópico para ser concluído, o diagram está no drive na pasta referente ao seminário

**Comment by Phe0** [comment]
V1
![fishbone](https://user-images.githubusercontent.com/31973465/63530531-060f6700-c4dd-11e9-9e08-ea542a6dd907.png)
