### ISSUE TITLE
TAP

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#12]
## Nome da Issue
TAP

## Descrição da Issue
Construir Termo de Abertura do Projeto

### Tasks:
- [x] Pesquisar estrutura da TAP
- [x] Fazer pesquisa que responda os campos da TAP
- [x] Elaborar documento

Exemplo:
 - https://translate-me.github.io/docs/documentos/gerencia/tap/

**Comment by pedro-prp** [comment]
Vou puxar o primeiro Tópico de Introdução

**Comment by MatheusBlanco** [comment]
Adicionado o histórico de revisão

**Comment by MatheusBlanco** [comment]
Adicionados critérios de sucesso aos objetivos

**Comment by guilhesme23** [comment]
Vou fazer a parte de estimativa de custos
