### ISSUE TITLE
Marca 

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#15]
## Nome da Issue
Marca

## Descrição da Issue
Definir marca do produto de software

### Tasks:
- [x] Definir Nome
- [x] Definir Logo
- [x] Definir Cores
- [x] Definir Fontes

**Comment by alanrslima** [comment]
Link para arquivo .xd que está sendo feito a identidade visual do app disponível [AQUI](https://drive.google.com/file/d/1MdkGDhXGsX4VwKLfLp2TsyIcCuPcnOrn/view?usp=sharing). Obs: Necessário possuir o Adobe XD.

**Comment by alanrslima** [comment]
As sugestões dos integrantes do grupo estão disponíveis [NESTE DOCUMENTO](https://docs.google.com/document/d/1k_ct5tSl6vlQ30ZuEBm6zLiiwabm4WGoOu5JzdUda2Y/edit?hl=en).

**Comment by Phe0** [comment]
logos no figma: https://www.figma.com/file/n91KQZjBAgN9qf8Uh1ktZd/Untitled?node-id=0%3A1

**Comment by Phe0** [comment]
Logo V1
![Group 2 1](https://user-images.githubusercontent.com/31973465/63463718-21726780-c434-11e9-9831-899567a78485.png)

logo V2
![Group 13](https://user-images.githubusercontent.com/31973465/63464046-d016a800-c434-11e9-9bf7-c86ff179feec.png)


logo V3
![Group 12](https://user-images.githubusercontent.com/31973465/63464009-b4ab9d00-c434-11e9-8406-0d43c189af58.png)

Opções com o nome
![Group 9 1](https://user-images.githubusercontent.com/31973465/63463779-436bea00-c434-11e9-8816-128f80f6e952.png)
![Group 10 1 (3)](https://user-images.githubusercontent.com/31973465/63463788-48c93480-c434-11e9-822a-df5187c88367.png)
![Group 10 2](https://user-images.githubusercontent.com/31973465/63463795-4bc42500-c434-11e9-962d-1b63644b27f7.png)
![Group 9 3](https://user-images.githubusercontent.com/31973465/63463802-4e267f00-c434-11e9-832b-0e72c711c1c8.png)

logo V4
![Group 11 13 (1)](https://user-images.githubusercontent.com/31973465/63463928-92b21a80-c434-11e9-94ea-cd8e288e680c.png)

Opções de cor

![Screenshot from 2019-08-21 16-50-43](https://user-images.githubusercontent.com/31973465/63463960-9a71bf00-c434-11e9-95c7-06c205231605.png)

**Comment by Phe0** [comment]
[Manual de Identidade Visual.pdf](https://github.com/fga-desenho-2019-2/Wiki/files/3530965/Manual.de.Identidade.Visual.pdf)

**Comment by guilhesme23** [comment]
Essa issue ja pode ser fechada?
