### ISSUE TITLE
Pesquisas solicitadas pela Professora

### ISSUE THREAD

**Issue by devsalula** [fga-desenho-2019-2/Wiki#16]
## Nome da Issue
Pesquisas solicitadas pela Professora

## Descrição da Issue
Pesquisar sobre alguns assuntos comentados pela Professora na Dinâmica do dia 19/08.

### Tasks:
- [x] Pesquisar sobre App's semelhantes na China
- [ ] Pesquisar sobre Legislação que pode interferir no App

**Comment by devsalula** [comment]
Artigos sobre a popularização do QR Code na China:
https://economictimes.indiatimes.com/tech/internet/transacting-in-china-is-a-joy-with-the-all-pervasive-qr-code-and-anywhere-delivery/articleshow/65544560.cms?from=mdr

https://www.chriskranky.com/wechat-moves-restaurant-speed-efficiency-savings/

https://www.youtube.com/watch?v=cj2Fh8aX148

https://www.youtube.com/watch?v=hpu9wRq89wg

**Artigo interessante**:
https://iaiest.com/dl/journals/8-%20IAJ%20of%20Innovative%20Research/v2-i12-dec2015/paper1.pdf

**Comment by shayanealcantara** [comment]
@devsalula Fiz uma contribuição na pesquisa e separei o arquivo na pasta de Iniciativas extra.

**Comment by shayanealcantara** [comment]
@devsalula qual é o status dessa issue? Você ainda vai pesquisar o 2º tópico?

**Comment by devsalula** [comment]
@ebmm01 pode colocar aqui a sua pesquisa?

**Comment by ebmm01** [comment]
LGPDP => http://www.planalto.gov.br/ccivil_03/_Ato2015-2018/2018/Lei/L13709.htm

Vou pesquisar se há outras regulamentações específicas que possam abranger nosso projeto

Edit: Um link muito bom com diversas leis e regulamentações: 
http://www.inpi.gov.br/menu-servicos/programa-de-computador/legislacao-programa-de-computador

**Comment by MatheusBlanco** [comment]
Coé @ebmm01 , sobe pra wiki lá, man

**Comment by shayanealcantara** [comment]
Não vai rolar, pelo jeito. Estou fechando
