### ISSUE TITLE
Seminário Kanban

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#21]
### Descrição da Issue
Realizar um seminário sobre a metodologia Kanban.

### Tasks:
- [x] 5W2H
- [x] Pesquisar melhorias na metodologia
- [x] Pesquisar empresas que utilizam o Kanban
- [x] Construir o slide

**Comment by guilhesme23** [comment]
Vou pegar a parte de "porque" do 5w2h

**Comment by MatheusBlanco** [comment]
Vou pegar a parte de "o que" do 5w2h, se ninguém tiver pego ainda.

**Comment by devsalula** [comment]
Estou redigindo o _How much_.

**Comment by ebmm01** [comment]
@MatheusBlanco eu já tinha pego o "O que"  :(
Mas posso ficar om o "How" se fizer questão

**Comment by MatheusBlanco** [comment]
Perdão, me esqueci que já tinha pego esse. Eu posso ficar com o 'How'

**Comment by alanrslima** [comment]
Fico responsável pelo "Onde"

**Comment by devsalula** [comment]
Material fornecido pela Professora:
https://pt.coursera.org/lecture/uva-darden-agile-team-management/kanban-fundamentals-Gb4M2
https://www.culturaagil.com.br/kanban-do-inicio-ao-fim/
https://www.youtube.com/watch?v=jf0tlbt9lx0

**Comment by silvasara** [comment]
Concluí o doc com as empresas que utilizam o kanban
