### ISSUE TITLE
API de pagamento

### ISSUE THREAD

**Issue by ebmm01** [fga-desenho-2019-2/Wiki#22]
## Descrição da Issue
Procurar API's de pagamento e verificar como elas funcionam e precificação

### Tasks:
- [ ] Listar API's de pagamento
- [ ] Descrever o funcionamento delas e precificação

**Comment by Phe0** [comment]
Pesquisar:
 - google pay
 - pag seguro
 - paypal
 - picpay
 - cartão de crédito
 - cartão de débito
 - vale alimentação
 - ali pay

**Comment by ebmm01** [comment]
O google pay parece ser bem burocrático de se usar, tendo um fluxo mais ou menos assim: 

tutorial > verificações no ambiente de TEST > eles veem se está tudo certo e liberam pro ambiente de produção > mais verificações > liberar 100%

https://developers.google.com/pay/api/web/overview?hl=pt-br

O paypal não é muito diferente, apesar de ser _um pouco_ menos burocrático:

https://www.paypal-brasil.com.br/desenvolvedores/tutorial/credenciais-de-api-e-certificado-de-api-completo/

Vou documentar esses e mais alguns e adicionar tudo à wiki

**Comment by Phe0** [comment]
Sugestão: https://docs.pagar.me/docs

**Comment by leossb36** [comment]
Não será viável o uso de API para pagamento, pois o tempo para produção não será suficiente para tratamento do que foi elicitado, devido a complexidade.
