### ISSUE TITLE
Possíveis Arquiteturas

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#23]
## Nome da Issue
Possíveis Arquiteturas

## Descrição da Issue
Pesquisar arquiteturas de software que possamos utilizar durante o projeto

**Comment by devsalula** [comment]
https://www.youtube.com/watch?v=vNHpsC5ng_E&feature=youtu.be
Livro sobre padrões de projetos: https://integrada.minhabiblioteca.com.br/#/books/9788577800469/pageid/6
https://integrada.minhabiblioteca.com.br/#/books/9788577800476/pageid/0
@guilhesme23 subiu mais um livro sobre design patterns no Drive

**Comment by devsalula** [comment]
Arquitetura de Micro-serviços do Ifood, ver a partir do minuto 8: https://www.infoq.com/br/presentations/gerenciamento-de-dados-com-micro-servicos-e-a-experiencia-do-ifood/

**Comment by devsalula** [comment]
Eu e o @guilhesme23 rabiscamos um possível padrão de arquitetura para o projeto:
![12abe076-40ac-4db0-84e3-3da7a5526316](https://user-images.githubusercontent.com/35435199/63958982-90b61000-ca61-11e9-8e87-aca8795c2cb1.jpeg)
![0d842716-c718-4a59-a3aa-930196d9c921](https://user-images.githubusercontent.com/35435199/63959021-a4fa0d00-ca61-11e9-88f4-cdad2389368d.jpeg)

**Comment by shayanealcantara** [comment]
Arquitetura terá início hoje (02/09) à noite.

**Comment by guilhesme23** [comment]
Ficou decidido por Microsserviços mesmo.
