### ISSUE TITLE
Testes de Usabilidade

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#25]
## Nome da Issue
Testes de Usabilidade

## Descrição da Issue
Realizar testes de usabilidade com o protótipo de alta fidelidade

### Tasks:
- [x] Montar script
- [x] Realizar testes
- [x] Fazer análise dos testes

**Comment by pedro-prp** [comment]
Acabei de escrever um roteiro básico, ta no drive.

**Comment by shayanealcantara** [comment]
@pedro-prp, pode adicionar o script criado em um arquivo sobre o teste de usabilidade no tópico de iniciativas extras, por favor?

**Comment by pedro-prp** [comment]
Posso sim, farei isso.
