### ISSUE TITLE
Metodologia da equipe

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#27]
## Nome da Issue
Metodologia da equipe

## Descrição da Issue
Pesquisar pontos fortes e fracos de diferentes ferramentas e metodologias para que possamos criar nossa metodologia de trabalho para o projeto.

### Tasks:
- [x] Listar metodologias
- [x] Elevancar pontos fortes e fracos de cada metodologia

**Comment by silvasara** [comment]
Sugestão: BDD
https://www.devmedia.com.br/desenvolvimento-orientado-por-comportamento-bdd/21127
https://dtidigital.com.br/blog/bdd-como-metodologia-agil/

**Comment by silvasara** [comment]
Sugestão: TDD
https://www.devmedia.com.br/test-driven-development-tdd-simples-e-pratico/18533

**Comment by Phe0** [comment]
https://brodzinski.com/2012/07/cadences-iterations.html

Visando a dificuldade da equipe em fazer reuniões presenciais, trabalhar com cadências diferentes pode ser uma solução viável

**Comment by Phe0** [comment]
https://www.cin.ufpe.br/~scbs/metricas/seminarios/GQM_texto.pdf

Definir GQMs para estabelecer formas de medir o produto e a equipe

**Comment by Phe0** [comment]
https://www.daxx.com/blog/development-trends/top-software-development-metrics

Possíveis métricas a serem utilizadas no processo de desenvolvimento de software

**Comment by shayanealcantara** [comment]
Até o momento foram apontadas as possibilidades:

- Kanban(zenhub)
- PR pra código
- Sem daily
- CI/CD
- Pareamento
- Sem pontuação pra us 
- Métricas para desempenho (quais?)
- Planning semanal (rápida definição de tarefas)
- Review mensal (planejamento das tarefas do mês)
- Lean (como será no contexto do projeto?)

**Comment by shayanealcantara** [comment]
Decisão na issue #43 .
