### ISSUE TITLE
Criar diagrama BPM sobre Elicitação de Requisitos

### ISSUE THREAD

**Issue by silvasara** [fga-desenho-2019-2/Wiki#39]
## Descrição da Issue
Criar diagrama usando a notação BPM sobre o processo Elicitação de Requisitos.

### Tasks:
- [x] Mapear o processo cumprindo a notação BPM
- [x] Adicionar imagem na pasta diagramas-bpm

**Comment by MatheusBlanco** [comment]
Feito
