### ISSUE TITLE
Definir arquitetura do projeto

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#44]
## Nome da Issue
Definir arquitetura do projeto

## Descrição da Issue
Definir e dar início à modelagem da arquitetura a ser usada durante o projeto.

### Tasks:
- [x] Definir tecnologias
- [x] Modelar esboço da arquitetura 
- [x] Documentar as decisões

## Relacionada à issue #23

**Comment by shayanealcantara** [comment]
Tecnologias que serão usadas: Vue + Django Rest

**Comment by guilhesme23** [comment]
A arquitetura escolhida foi microsserviços

**Comment by guilhesme23** [comment]
## Esboço inicial da arquitetura

![image](https://user-images.githubusercontent.com/32804970/64137665-08709b80-cdd0-11e9-801f-714054bc4924.png)
![image](https://user-images.githubusercontent.com/32804970/64137670-0dcde600-cdd0-11e9-8a20-43a6931f6eee.png)
