### ISSUE TITLE
Diagrama de classe para o microsserviço do usuário

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#45]
## Descrição da Issue
Diagrama de classe para o microsserviço do usuário.

### Tasks:
- [x] Criar modelo usando a ferramenta Draw.io
- [x] Documentar o diagrama

**Comment by shayanealcantara** [comment]
@silvasara irá refatorar esta issue.

**Comment by silvasara** [comment]
O diagrama foi corrigido
