### ISSUE TITLE
Questionário

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#5]
## Nome da Issue
Questionário

## Descrição da Issue

Realizar um google forms em que a gente pudesse atingir muitas pessoas e tirar dados pra entender melhor o contexto. O objetivo é entender mais a nível de problema, será que a galera realmente acha ruim as filas? na hora de pedir ou de pagar? ou será que o problema maior é chamar o garçom pra pagar. Coisas desse tipo.

### Tasks:
- [x] Elaborar perguntas
- [x] Construir google forms
- [x] Divulgar Questionário
- [x] Analisar Respostas

**Comment by shayanealcantara** [comment]
Após reunião com a equipe no dia 19/08, houve a necessidade de elaborar mais perguntas para complementar as suposições do problema abordado.

**Comment by shayanealcantara** [comment]
O questionário foi divulgado hoje 20/08 para grupos variados, visto que o público alvo é diverso.
