### ISSUE TITLE
Criar diagrama dos componentes do front-end

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#50]
## Descrição da Issue
Criar diagrama dos componentes do front-end

### Tasks:
- [x] Criar modelo usando a ferramenta Draw.io
- [ ] Documentar o diagrama

**Comment by Phe0** [comment]
Rascunho inicial do diagram de componentes,
feito por @Phe0 e @guilhesme23 

![photo5174866229796644927](https://user-images.githubusercontent.com/31973465/64828369-8554ff80-d59e-11e9-8a39-9b0c16f21223.jpg)

**Comment by shayanealcantara** [comment]
Falta só documentar na wiki @guilhesme23 @Phe0
