### ISSUE TITLE
Atualizar diagrama de bancos

### ISSUE THREAD

**Issue by silvasara** [fga-desenho-2019-2/Wiki#51]
## Atualizar diagrama de bancos
Atualizar o diagram de bancos de acordo com a arquitetura definida pelo grupo

### Tasks:
- [x] Pagamento
- [x] Usuário
- [x] Restaurante
- [x] Pedido

**Comment by shayanealcantara** [comment]
hotfix:
- [x] Reestruturar documentação
- [x] Incluir novo modelo de dados
