### ISSUE TITLE
Quadro de Conhecimentos por Sprint

### ISSUE THREAD

**Issue by devsalula** [fga-desenho-2019-2/Wiki#54]
## Descrição da Issue
Documentar o quadro de conhecimentos toda semana nos comentários da Issue

Link do documento: https://docs.google.com/spreadsheets/d/1IekQLjz2NauicclkujrQ68OtLXYiF5fICv9ZgFeQYfY/edit?usp=sharing

**Comment by shayanealcantara** [comment]
Não aconteceu em nenhuma sprint. Estou fechando.
