### ISSUE TITLE
Criar diagrama de sequência sobre o microsserviço de pedidos

### ISSUE THREAD

**Issue by shayanealcantara** [fga-desenho-2019-2/Wiki#57]
## Descrição da Issue
Criar diagrama de sequência sobre o microsserviço de pedidos segundo a notação.

### Tasks:
- [ ] Utilizar a ferramenta x
- [ ] Documentar o diagrama

**Comment by shayanealcantara** [comment]
qual é o status dessa issue?

**Comment by Phe0** [comment]
@shayanealcantara já está na wiki

**Comment by shayanealcantara** [comment]
fechando a issue então
