### ISSUE TITLE
Entrevistas

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#7]
## Nome da Issue
Realizar entrevistas

## Descrição da Issue
Realizar entrevistas com possíveis usuários e donos, gerentes e atendentes de restaurantes para coletar os os principais problemas enfrentados nos restaurantes e praça de alimentação.

### Tasks:
- [x] Elaborar perguntas a serem feitas
- [x] Realizar entrevista
- [x] Documentar entrevista
- [x] Realizar análise das respostas

**Comment by MatheusBlanco** [comment]
Documento prévio de perguntas a serem feitas: https://docs.google.com/document/d/1uDTis8wMqT7XwvufhSvCxy-6qURbyft0T8i4e5oDm4U/edit?usp=sharing

@leossb36 e @pedro-prp , por favor revisem e adicionem as perguntas que acharem necessárias.
