### ISSUE TITLE
US08 - [Back-end] CRUD Restaurantes

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-desenho-2019-2/Wiki#72]
**Descrição**
Eu, como restaurante, gostaria de poder cadastrar meu estabelecimento na aplicação, informando todos os principais dados necessários, para que eu possa cadastrar meus produtos.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- [x] Deverá ter o campo nome;
- [x] Deverá ter o campo e-mail de contato;
- [x] Deverá ter o campo telefone de contato;
- [x] Deverá ter o campo telefone de CNPJ;
- [x] Deverá salvar as informações desejadas no banco de dados da aplicação;
- [x] Funcionalidade testada;
- [x] Criada no framework DJANGO REST;
- [x] Não utilizar Viewsets.

**Tarefas**
- [x] É testável;
- [x] Criar métodos relativos ao CRUD (CREATE, UPDATE, READ, DELETE);

**Comment by silvasara** [comment]
PR criado para avaliação: https://github.com/fga-desenho-2019-2/restaurant-service/pull/1
