### ISSUE TITLE
US09 - [Back-end] CRUD Pedidos

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-desenho-2019-2/Wiki#73]
**Descrição**
Eu, como cliente, gostaria de poder realizar pedidos nos restaurantes de minha escolha, 
 para que eu possa desfrutar do alimento desejado.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- [x] Deverá ter o campo **nome** do pedido;
- [x] Deverá ter o campo **descrição** do pedido;
- [x] Deverá ter o campo **quantidade**;
- [x] Deverá ter o campo **adicionais**;
- [x] Deverá salvar os dados no banco de dados;
- [x] Funcionalidade testada;
- [x] Criada no framework DJANGO REST;
- [x] **Não utilizar Viewsets;**

**Tarefas**
- [x] É testável;
- [x] Criar métodos relativos ao CRUD (CREATE, UPDATE, READ, DELETE);
- [x] Registrar as informações no banco de dados da aplicação;
- [x] Criar os métodos no formato de API.

**Comment by silvasara** [comment]
PR com duas apovações e feito merge na develop
