### ISSUE TITLE
US05 - [Back-end] Configurar ambiente docker

### ISSUE THREAD

**Issue by MatheusBlanco** [fga-desenho-2019-2/Wiki#80]
**Descrição**
Eu, como desenvolvedor, gostaria de poder rodar minhas aplicações de maneira simples e direta a partir de um único container para que eu não precise rodar individualmente cada um dos serviços necessários e possa acelerar o processo de desenvolvimento.

**Critérios de Aceitação** [?](http://www.metodoagil.com/historias-de-usuario/)
- [x] Deverá ter conexão com o banco de dados;
- [x] Deverá poder rodar o backend da aplicação;
- [ ] Deverá poder rodar o frontend da aplicação;
- [ ] Deverá poder se comunicar com outros containers da aplicação;
- [x] Funcionalidade testada;

**Tarefas**
- [x] É testável;
- [x] Criar o container utilizando Docker;
- [x] Adicionar os serviços e pacotes necessários para que se possa rodar a aplicação;
- [x] Conectar o container com o banco de dados;
- [ ] Conectar o container com outros containers.

**Comment by silvasara** [comment]
@leossb36 chega de mexer no docker
