### ISSUE TITLE
Melhorias docker

### ISSUE THREAD

**Issue by leossb36** [fga-desenho-2019-2/Wiki#81]
## Nome da Issue
Melhorias docker.

## Descrição da Issue
Otimizar container e realizar tarefas para cobertura de código. 

#### para todos os microsserviços
- [ ] Configurar Code climate
- [ ] Criar usuario non-root para docker
- [ ] Inserir bot github de cada um dos repositorios
- [ ] Criar Makefile 
## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

## Labels
A issue deve ser marcada com uma ou mais tags adequadas, para fins de rastreamento do projeto.

**Comment by guilhesme23** [comment]
Não entendi bem alguns pontos da issue, não entra em conflito com a issue #76 ?

Inclusive a ferramenta que seria utilizada era o gitlab-ci não?

**Comment by leossb36** [comment]
Ah, perdão, eu coloquei bem no automatico, devido a falta de conhecimento no gitlab-ci, vou corrigir

**Comment by leossb36** [comment]
O restante se mantem, pq a finalidade e acompanhamento de cada um dos containers e tirar a limitação do usuario root(no caso eu vou fazer essa parte), ai deixei como nota
