### ISSUE TITLE
5W2H

### ISSUE THREAD

**Issue by Phe0** [fga-desenho-2019-2/Wiki#9]
## Nome da Issue
5W2H

## Descrição da Issue
Elaborar 5W2H para manter o grupo alinhado a respeito do produto.
 
### Tasks:
- [x] What
- [x] Why
- [x] Who
- [x] When
- [x] How
- [x] How Much
- [x] Where

**Comment by silvasara** [comment]
O documento foi adicionado com na wiki com os tópicos: Introduço, What, How, Where e Referências
