### ISSUE TITLE
[Back-end] CRUD de Categorias do Restaurante

### ISSUE THREAD

**Issue by guilhesme23** [fga-desenho-2019-2/Wiki#95]
## Nome da Issue
CRUD de Categorias do Restaurante

## Descrição da Issue
Criar as views para o CRUD de categorias de restaurantes

### Tasks:
- [ ] Criar views para as models de Categorias de Restaurantes

### Critérios de Aceitação
- [ ] Código passando em testes estáticos
- [ ] Código testado

**Comment by silvasara** [comment]
[PR](https://github.com/fga-desenho-2019-2/restaurant-service/pull/6) aberto para review
