### ISSUE TITLE
Seleção de Padrões

### ISSUE THREAD

**Issue by devsalula** [fga-desenho-2019-2/Wiki#97]
Por questão de organização, informar o padrão que será utilizado na sua issue e filtrá-los.

Colocar nessa planilha:
https://docs.google.com/spreadsheets/d/1XPG5addYKdGNODJS_qgcNzORM7tVAWo9oRLrmG0bQy0/edit#gid=1889659989

**Comment by shayanealcantara** [comment]
Link bom para estudos: https://brizeno.wordpress.com/padroes/

**Comment by shayanealcantara** [comment]
Dicas do Elias:

- No front é usado Singleton (vuex), observer (watchers do vue) e dá pra abordar outros emergentes pro próprio vue. No django, template method. ( Tem outros que vou tentar ver hoje, mas não sei de cabeça)

- Dá pra usar memento pros pedidos, envio de email tem um que esqueci o nome é em testes dá pra aplicar os criacionais tipo factory

- No front dá pra usar o facade na parte dos services

- Se formos pensar em cupons de desconto dá pra usar outros padrões tbm, tipo proxy

**Comment by Phe0** [comment]
## Possíveis Padrões a serem aplicados no front:

### Criacionais

 - Factory -> Para criar diferentes tipos de card
 - Builder -> Para criar formas diferentes do RestaurantCard (squared e extended)
 - Singleton -> inerente à aplicação por conta do uso do localStorage e Vuex
 - Multiton -> inerente à aplicação por conta de criação multipla de componentes por meio do v-for

### Estruturais 
 - Composite -> inerente à aplicação por conta da estrutura padrão do vue
 - Facade -> é aplicável para facilitar a interface com os services
 - Flyweight -> inerente à aplicação, em vez de se criar várias variáveis iguais, elas são passadas pela árvore de componentes atravéz das props 

### Emergentes
 - Container/Presentional components -> manter toda lógica dentro do "container" e passar o state para os "presentional" components apenas para serem colocados na tela. Componentes "presentional" não devem manter estado fora dos objetos de entrada
- Prop validation -> validar props é essencial para garantir o funcionamento da aplicação
- HOC -> precisa estudar melhor, não entendi direito 
### Anti-patterns
 - Componentes filhos mudarem props, props devem ser a fonte da verdade 
 - Usar data como objeto em vez de função, isso faz com que todas as cópias do componente compatilhem o mesmo data
 - Nomear componentes com apenas uma palavra, podem conflitar com elementos html nativos

**Comment by shayanealcantara** [comment]
Outra issue será criada para documentar
